FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 \
    libgl1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements_api.txt .

RUN python -m pip install --upgrade pip && \
    pip install --default-timeout=1000 --no-cache-dir -r requirements_api.txt

COPY api/main.py .
COPY model.pkl .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]